server:
  port: 8085

spring:
  application:
    name: SouthAmericanBank

  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/db_bancksouth
    username: root
    password: mysql

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
